 We use C because conda manages our Python version
language: c

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false


# Configure the build environment. Global varibles are defined for all configurations.
env:
    global:
        - PREVIOUS_NUMPY=1.10.4
        - PYTHON_VERSION=2.7
        - TEST_MODE='offline'
        - NUMPY_VERSION='stable'
        - ASTROPY_VERSION='stable'
        - MAIN_CMD='python setup.py'
        - CONDA_CHANNELS='astropy astropy-ci-extras conda-forge'
        - CONDA_DEPENDENCIES='sunpy'
        - PIP_DEPENDENCIES='suds-jurko sphinx-gallery'

    matrix:
        - PYTHON_VERSION=2.7 SETUP_CMD='egg_info' 
        - PYTHON_VERSION=3.4 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.5 SETUP_CMD='egg_info'
        - PYTHON_VERSION=2.7 SETUP_CMD='test'
        - PYTHON_VERSION=3.4 SETUP_CMD='test'
        - PYTHON_VERSION=3.5 SETUP_CMD='test'
